[[staff]]
name = "Jim Mackenzie"
title = "Vice President of Trust and Safety"
picture = "jim.jpg"
bio = """
Jim brings a calm optimism to building a safer, kinder Internet. He has worked with the Safety team for Matrix.org since 2021, after joining from 37signals. Jim works on policy and process, tooling and techniques for Matrix.org and Matrix as a whole.
"""

[[staff]]
name = "Andy Piper"
title = "Senior Developer Relations Engineer"
picture = "andy.jpg"
website = "https://andypiper.co.uk"
linkedin = "https://linkedin.com/in/andypiperuk/"
fediverse = "https://macaw.social/@andypiper"
bio = """
Andy is a technologist, communicator, community builder, and long-time believer in open protocols doing useful things in the real world. He likes technology best when people can understand it, build on it, and choose how they use it. At the Foundation, he helps to tell the story of Matrix, connects its technical work with the wider ecosystem, and supports the community around an open and interoperable future for communication.
"""

[[staff]]
name = "Travis Ralston"
title = "Director of Standards Development"
picture = "travis.jpg"
linkedin = "https://www.linkedin.com/in/travisralston/"
fediverse = "https://mstdn.ca/@travisr"
bio = """
Travis is an avid volunteer, free software developer, Spec Core Team (SCT) member, makerspace director, and collector of strange hobbies. Travis started writing PRs for Matrix in 2016 to support his local makerspace in switching away from IRC, and has continued contributing to Matrix since. Travis’ latest role supports the SCT in operating the Matrix Spec Change (MSC) process, and engages with other standards bodies to advocate for and support Matrix.
"""

[[staff]]
name = "Denise Almeida"
title = "Data Protection Officer"
picture = "denise.jpg"
website = "https://denisealcom.wordpress.com/"
linkedin = "https://www.linkedin.com/in/denisersalmeida/"
bio = """
Denise is passionate about justice and inclusion, which translates into her work in public policy and compliance. She has been working for Element, and Matrix.org, since early 2020 as their designated DPO and compliance lead. Denise is also in the final stages of her PhD, which focuses on the intersection of privacy, privilege and technology.
"""
