[book]
authors = ["The Matrix.org Foundation C.I.C."]
language = "en"
multilingual = false
src = "src"
title = "Matrix Widget Implementors Guide"

[output.html]
theme = "../theme"
git-repository-url = "https://github.com/matrix-org/matrix.org/tree/master/implementation-guides/widgets"

[preprocessor.links]

[preprocessor.index]
