name: Update public instances
on:
  schedule: [{cron: "0 0 * * *"}]

jobs:
  run:
    name: Update public instances
    runs-on: ubuntu-latest
    steps:
      - name: Checkout matrix.org source
        uses: actions/checkout@v4
        with:
          path: 'morg'

      - name: Checkout the public instance updater
        uses: actions/checkout@v4
        with:
          repository: 'thibaultamartin/public-instances-updater'
          path: 'piu'

      - name: Update public instance data on the runner
        run: |
          cp morg/content/public-instances/instances.toml piu/instances.toml
          cd piu && yarn && yarn run update && cd ..
          cp piu/instances.toml morg/content/public-instances/instances.toml

      # Delete the if before merging to main
      - name: Commit and push data (scheduled)
        run: |
          git config --global user.name "GitHub CI"
          git config --global user.email "noreply@matrix.org"
          git add content/public-instances/instances.toml
          git commit -m "Update instances.toml"
          git push
        working-directory: morg
